### ISSUE TITLE
Scoring system

### ISSUE THREAD

**Issue by MGZeroes** [HKA-Basketball/bosconian#3]
- How does scoring work?
- What do we all get points for?
- How many points do I get for each award?

**Comment by deco42** [comment]
Score Table:

    Asteroid:
        10 PTS
    Cosmo-Mine:
        20 PTS
    I-Type (Missile):
        50 PTS
    P-Type:
        60 PTS
    E-Type:
        70 PTS
    Spy Ship:
        Mystery
    Enemy Base Cannon:
        200 PTS
    Enemy Base:
        1500 PTS
